version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: app-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  flyway:
    image: flyway/flyway:9
    container_name: app-flyway
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - FLYWAY_USER=${DB_USER}
      - FLYWAY_PASSWORD=${DB_PASSWORD}
    command: -configFiles=/flyway/conf/flyway.conf migrate
    volumes:
      - ./db/migrations:/flyway/sql
      - ./docker/flyway/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge